### ISSUE TITLE
How to run the actual bencharks?

### ISSUE THREAD

**Issue by KaiserKarel** [mmaker/zkalc#7]
I'm looking for the script that invokes the actual benchmarks to evaluate the compiler options used.

**Comment by asn-d6** [comment]
Hello,

we tried to document this in https://zka.lc/about but perhaps we didn't do a really good job because it gets lost in the noise.

Anyhow, you run the benchmarks by doing `make` in the `backend/` directory. You can see the [Makefile](https://github.com/asn-d6/zkalc/blob/main/backend/Makefile) to learn the actual commands being run (basically `cargo criterion`).

**Comment by KaiserKarel** [comment]
Gotcha. It might be interesting to run these benchmarks with LTO=1 and target-cpu=native.

**Comment by mmaker** [comment]
Hey @KaiserKarel ! I'm not sure this would be really useful.. I'd expect end-user libraries to enable parallelism and asm backends, but do they also ship with cpu-native and optimized lto? Would you like to make a pull request for it? Creating a`.cargo` folder similarly to what I did here would probably do the job! https://github.com/arkworks-rs/gemini/tree/main/.cargo
